fix full file

diff --git a/.github/workflows/self_heal.yml b/.github/workflows/self_heal.yml
--- a/.github/workflows/self_heal.yml
+++ b/.github/workflows/self_heal.yml
@@ -37,32 +37,32 @@ jobs:
         # python -m pip install --upgrade pip
         pip3 install -r requirements.txt
         # pip install openai github
-    # - name: Run python script
-    #   run: |
-    #     pwd
-    #     ls -la
-    #     python3 bug.py > /home/runner/work/self-heal-CI-CD/self-heal-CI-CD/error.txt 2>&1
-        
-    - name: Dynamically find and run Python files
+    - name: Run python script
       run: |
-        exit 0
-        # Find all Python files (e.g., *.py) in the repository, excluding this workflow file
-        for python_file in $(find /home/runner/work/self-heal-CI-CD/self-heal-CI-CD/src -name "*.py"); do
-        echo "Running $python_file"
+        pwd
+        ls -la
+        python3 src/bug.py > /home/runner/work/self-heal-CI-CD/self-heal-CI-CD/error.txt 2>&1
         
-        # Create a unique error log per file
-        error_log="/home/runner/work/self-heal-CI-CD/self-heal-CI-CD/$(basename "$python_file").error.txt"
+    # - name: Dynamically find and run Python files
+    #   run: |
+    #     exit 0
+    #     # Find all Python files (e.g., *.py) in the repository, excluding this workflow file
+    #     for python_file in $(find /home/runner/work/self-heal-CI-CD/self-heal-CI-CD/src -name "*.py"); do
+    #     echo "Running $python_file"
+        
+    #     # Create a unique error log per file
+    #     error_log="/home/runner/work/self-heal-CI-CD/self-heal-CI-CD/$(basename "$python_file").error.txt"
 
-        python3 "$python_file" > "$error_log" 2>&1
+    #     python3 "$python_file" > "$error_log" 2>&1
 
-        if [ $? -ne 0 ]; then
-          echo "Error running $python_file! See $error_log"
-        fi
-        done
+    #     if [ $? -ne 0 ]; then
+    #       echo "Error running $python_file! See $error_log"
+    #     fi
+    #     done
 
     - name: Run self-healing script
       id: self_heal
-      # if: failure()
+      if: failure()
       env:
         GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
@@ -70,16 +70,9 @@ jobs:
         pwd
         ls -la
         
-        # cat /home/runner/work/self-heal-CI-CD/self-heal-CI-CD/error.txt
-        # python self_heal.py
+        cat /home/runner/work/self-heal-CI-CD/self-heal-CI-CD/error.txt
+        python self_heal.py
 
-    - name: get step status
-      if: ${{ steps.self_heal.outcome == 'success'}}
-      id: job_status
-      run: echo ${{ steps.self_heal.outcome == 'success'}}
-
-    - name: Slack notification
-      if: ${{ steps.self_heal.outcome == 'success'}}
-      run: |
-        echo ${{ steps.self_heal.outcome }}
         curl -X POST -H 'Content-type: application/json' --data '{"message":"Self-healing workflow completed. PR created with the fix!\n${{ env.PR_LINK }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+
+        
